podaac/tutorials

- notebooks/harmony subsetting/Harmony L2 Subsetter.ipynb
> Update Harmony L2 Subsetter.ipynb

- notebooks/Cloud L2SS subset and plot - JH.ipynb
changed
import xarray as xa
to 
import xarray as xr
> updated import xarray statement

- notebooks/l2-regridding/reprojection notebook.ipynb
changed import xarray as xa to import xarray as xr. updated the 2 xa.open_data calls
> Update reprojection notebook.ipynb

- notebooks/meetings_workshops/workshop_osm_2022/S6_OPeNDAP_Access_Gridding.ipynb
I introduced a small bug in this download function during my last push...oops
Could you please merge this one too Jinbo :)
> fix bug introduced during last push...oops

- notebooks/meetings_workshops/swot_ea_hackweek_2022/environment.yml
uploading SWOT EA hackweek PODAAC tutorials from Cassie and Matt. environment.yml is for the HLS tutorials.
> uploading SWOT EA hackweek PODAAC tutorials

- notebooks/AmazonRiver_Estuary_Exploration.ipynb
- notebooks/HUC Feature Translation Service Examples.ipynb
- notebooks/SWORD River Data Static Map-Updated.ipynb
Some of the tutorials had newer, more relevant versions and so I added a link at the top of the old tutorials to the new.
> Linking old and new versions of notebooks

- notebooks/SWOT-EA-2021/Estuary_explore_inCloud_zarr.ipynb
Updating this notebook to use the harmony-py package
> Updating to Harmony-py

- notebooks/sentinel-6/Access_Sentinel6_By_CyclePass.ipynb
- notebooks/sentinel-6/Access_Sentinel6_NRT.ipynb
Change to Sentinel 6 dataset instead of stand in datasets
> Update s6 tutorials

- .github/workflows/quarto-publish.yml
- .quarto/xref/49fffb79
- _import/assets.json
- _import/environment.yml
- _import/quarto_import.py
- _import/test_quarto_import.py
- _quarto.yml
- _site/index.html
- _site/quarto_text/CloudOptimizedExamples.html
- _site/quarto_text/DatasetSpecificExamples.html
- _site/quarto_text/SWOT.html
- _site/quarto_text/Tutorials.html
- _site/sitemap.xml
added the Zarr examples and the SWOT oceanography direct access example to the tutorials github repo. Updated the quarto.yml to reflect new notebooks
> Add external notebooks

- _site/sitemap.xml
- quarto_text/Sentinel6MF.qmd
Add tutorial landing page for Sentinel-6 Michael Freilich
> create S6 markdown file

- quarto_text/DatasetSpecificExamples.qmd
add link on dataset specific examples to landing page of sentinel 6 MF
> add link to S6 landing page

- index.qmd
- quarto_text/TechGuides.qmd
Added some content to the tech guides section and linked to the history of podaac paper in the introductory landing page for the cookbook
> Add Tech Guides resources

- _quarto.yml
- quarto_text/DatasetSpecificExamples.qmd
- quarto_text/SMAP.qmd
Add landing page for SMAP tutorials - data in action notebook
> Add SMAP tutorial & landing page

- _quarto.yml
- quarto_text/GIS.qmd
Add GIS to tutorials section
add Julie as author to her notebook
> Add GIS section

- _quarto.yml
- quarto_text/DataSubscriberDownloader.qmd
- quarto_text/HowTo.qmd
- quarto_text/SMAP.qmd
Add in section pointing to PODAAC Data Subscriber/Downloader in the How to section of the Cookbook. Also added link to the DiA SMAP story in the SMAP landing page.
> Add in subscriber downloader to Cookbook

- _import/assets.json
- _quarto.yml
- external/Direct_Access_SWOT_sim_Oceanography.ipynb
- external/Direct_S3_Access_NetCDF.ipynb
- external/DownloadDopplerScattData.ipynb
- external/Downloader.md
- external/ECCO_cloud_direct_access_s3.ipynb
- external/ECCO_download_data.ipynb
- external/July_2022_Earthdata_Webinar.ipynb
- external/NASA_Earthdata_Authentication.ipynb
- external/Subscriber.md
- external/cof-zarr-reformat.ipynb
- external/insitu_dataviz_demo.ipynb
- external/zarr-eosdis-store.ipynb
- external/zarr_access.ipynb
- quarto_text/DataSubscriberDownloader.qmd
- quarto_text/HowTo.qmd
Data subscriber and downloader .md files and the earthdata search .md file are now rendered in the Cookbook How to section
> Update how tos with md files imported

- notebooks/GIS/Subscriber_nc_to_tif_SWOT.qmd
mention linux environment in requirements.
fix typo
> Update nc to geotiff instructions

- quarto_text/Webinars.qmd
Added 2020 webinar to list of webinars in cookbook
> added 2020 webinar

- _quarto.yml
- notebooks/Tutorials_TEMPLATE.ipynb
- notebooks/datasets/OPERA_GIS_Notebook.ipynb
- quarto_text/OPERA.qmd
Add OPERA page, also fix up a link in the SWOT notebook. Add link to github from cookbook in tutorial.
> Add OPERA page to Cookbook

- quarto_text/DatasetSpecificExamples.qmd
> add opera to dataset page

- _quarto.yml
- quarto_text/GHRSST.qmd
- quarto_text/OPERA.qmd
- quarto_text/SWOT.qmd
Add MUR opendap example
Add downloader/subscriber to OPERA
fix some text in the SWOT page
> Add text to dataset specific sections

- quarto_text/OPERA.qmd
remove SWOT GIS part that carried over accidentally
> fix OPERA page

- quarto_text/Tutorials.qmd
> Change title of tutorials page

- quarto_text/GIS.qmd
- quarto_text/OPERA.qmd
- quarto_text/SWOT.qmd
Added links to OPERA StoryMap on OPERA page and GIS page. Added link to Worldview youtube tutorial to OPERA page too.
> Add OPERA StoryMap

- notebooks/SearchDownload_SWOTviaCMR.ipynb
Implemented earthaccess package to simplify authentication, search, and download of data
> Edit Search and Download SWOT Notebook

- quarto_text/SWOT.qmd
> change CMR ref to earthaccess

- _quarto.yml
- quarto_text/Experimental.qmd
Link notebook that is in development to be shown at ESIP
> Add lambda links to in development section

- external/Direct_Access_SWOT_sim_Oceanography.ipynb
earthaccess was not listed in necessary packages so added it to list
> added earthaccess into necessary packages

- external/Direct_Access_SWOT_sim_Oceanography.ipynb
> Edit Swot oceanography Notebook

- notebooks/GIS/SWOTsample_CSVconversion.ipynb
- notebooks/SearchDownload_SWOTviaCMR.ipynb
- notebooks/sentinel-6/Access_Sentinel6_By_CyclePass.ipynb
- notebooks/sentinel-6/Access_Sentinel6_NRT.ipynb
Added earthaccess library into local notebooks for authentication, search, and download of data.
> Updated Notebooks with earthaccess

- .github/workflows/quarto-publish.yml
update so gh-pages only deploys when master branch is modified.
> update quarto-publish.yml 

- _quarto.yml
- notebooks/aws_lambda_sst/docs/documentation.md
- notebooks/aws_lambda_sst/podaac-lambda-invoke-sst-global-mean.ipynb
- quarto_text/Advanced.qmd
- quarto_text/Experimental.qmd
Put in AWS Lambda documentation and tutorial within advanced cloud section of the cookbook. Emptied the in development section
> Add Advanced Cloud Section

- notebooks/podaac_cmr_s3_links.ipynb
- Created a notebook to show how to get list of s3 links from a cmr query
> add notebook to query cmr and get s3 links for a collections

- notebooks/aws_lambda_sst/podaac-lambda-invoke-sst-global-mean.ipynb
Minor updates to text in notebook in advance of Earthdata Webinar
> Updates to introductory text in notebook

- notebooks/Tutorials_TEMPLATE.ipynb
Change auth to earthaccess, remove netrc req since earthaccess covers this.
> update template with earthaccess

- quarto_text/SWOT.qmd
for swot cal and nominal orbits
> Add tile boundary shapefile links

- index.qmd
Added DOI to main page of Cookbook
> Add DOI to Cookbook

- _quarto.yml
- gtm_code_body.html
- gtm_code_head.html
updated the .yml file to include
include-in-header: gtm_code_head.html
include-before-body: gtm_code_body.html
and created those files it references
> Add google tag manager code

- _quarto.yml
- quarto_text/SWOT.qmd
added Arnaud's workshop data story to cookbook, SWOT data version 1.1
> Add ref to Hydrocron and Arnaud's notebook

- quarto_text/CloudvsLocalWorkflows.qmd
- quarto_text/OPERA.qmd
- quarto_text/SWOT.qmd
- quarto_text/Webinars.qmd
webinars
cloud vs local workflows
swot release notes
> Add content to various places

- quarto_text/cheatsheet.qmd
This PR mirrors links updates made in NASA-Openscapes Cookbook [PR ](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/321)that is merged.
> Update cheatsheet.qmd links to slides in new GDrive location

- _quarto.yml
- index.qmd
- quarto_text/SWOT.qmd
update citation and add hydrocron tutorial to SWOT landing page
> Add hydrocron tutorial to cookbook

- notebooks/Advanced_cloud/dask_delayed_01.ipynb
- quarto_text/OPERA.qmd
link to OPERA external github, fix typo in hydrocron tutorial, add podaac contribution badge to dask notebook
> Add content

- quarto_text/OPERA.qmd
Updated OPERA short name for PODAAC Data Subscriber.
OPERA_L3_DSWX-HLS_PROVISIONAL_V1 to OPERA_L3_DSWX-HLS_V1.
> Update OPERA Short Name

- _quarto.yml
- notebooks/datasets/SWOT_L4_DAWG_SOS_DISCHARGE.ipynb
- notebooks/datasets/SWOT_L4_DAWG_SOS_DISCHARGE_gauges.ipynb
- notebooks/datasets/SWOT_L4_DAWG_SOS_DISCHARGE_gauges_plot_all.ipynb
- notebooks/datasets/SWOT_L4_DAWG_SOS_DISCHARGE_visualize.ipynb
Add links to github versions of notebooks in each SWORD notebook and update the sidebar to include discharge in the title
> Update Sidebar and links

- index.qmd
Apache 2.0 link and CC BY link
> Add license to cookbook

- quarto_text/GIS.qmd
Fixed extra space in GIS section.
> fixed_typo

- _quarto.yml
- notebooks/Advanced_cloud/kerchunk_recipes.ipynb
- quarto_text/Advanced.qmd
- quarto_text/CloudOptimizedFormats.qmd
Add kerchunk_recipes notebook. Restructure some of the notebooks under 'Advanced Cloud' into a sub-category 'Cloud Optimized Data Formats'.
> Add kerchunk_recipes notebook
